### ISSUE TITLE
Hook into ChatControl Pro for displaying emojis publicly.

### ISSUE THREAD

**Issue by mibby** [RadBuilder/EmojiChat#10]
Would it be possible to add a hook for ChatControl Pro to allow emojis to work?
https://www.spigotmc.org/resources/%E2%99%A3-chatcontrol-pro%E2%84%A2-format-and-filter-your-chat-1-7-10-1-15-1-holiday-sale.10258/

ChatControl formatting doesn't seem to allow emojis to be replaced via their shortcut or their long name (i.e. ``:smile:``). If I use commands such as Essential's ``/me`` or Essential's ``/msg`` to message myself, I can see the emoji fine. I can also see the emojis on signs perfectly fine. It's just typing in chat publicly, emojis do not appear or get replaced.

My ChatControl formatting is fairly simple.
```
  Chat:
    Player:
      Message: '{display_name}&f: '
      Hover_Event:
        Action: SHOW_TEXT
        Values:
        - '{player}'
    The_Rest:
      Message: '{message}'
```

Using ChatControl's admin chat channel command ``/chatcontrol ach test message :confused:`` shows the emoji fine in that chat channel. Again, it's just public chat that doesn't seem to display anything. :(
