### ISSUE TITLE
Emoji shortcuts are not match case sensitive, matching the first shortcut it finds.

### ISSUE THREAD

**Issue by mibby** [RadBuilder/EmojiChat#26]
EmojiChat 1.8.3
Paper dev 147 (Spigot 1.16.2)

### What steps will reproduce the issue?  
1. Add shortcuts.
2. Try to use shortcuts.
3. Don't get desired shortcuts.

Tried typing ``>:)`` in chat.

### What was supposed to happen?  
😈 should appear instead of 🙂 

### What happened instead?  
🙂 appears.

### Are any errors related to EmojiChat in your console or logs? If so, paste below.  
None.

### Any additional information that you would like to provide that may be relevant to the issue?  
```
shortcuts:
  slightly_smiling_face:
  - ':)'
  - '(:'
  - ':slightly_smiling:'
  - ':slight_smile:'
  smiling_imp:
  - '>:)'
```
